contact_links:
  - name: Ask Question 🙋
    url: https://github.com/maticnetwork/matic.js/discussions/categories/q-a
    about: Have any doubt ? Ask your question 
  - name: Show & Tell ⚡
    url: https://github.com/maticnetwork/matic.js/discussions/categories/show-and-tell
    about: Show everyone what you have made. This will motivate other users & us.
  - name: Ideas
    url: https://github.com/maticnetwork/matic.js/discussions/categories/ideas
    about: Have some idea, let's discuss.
  - name: General - anything
    url: https://github.com/maticnetwork/matic.js/discussions/categories/general
    about: Share anything with us. It might be an article, news or anything which is beneficial for community.
